apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro690-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pro690-app
  template:
    metadata:
      labels:
        app: pro690-app
    spec:
      containers:
        - image: dnglglmm/pro690-g13-argocd:sha-7e430b9200942182a74fc4f233c97184aa81112e
          name: pro690-app
          ports:
            - containerPort: 8080
