apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro690-app
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pro690-app
  template:
    metadata:
      labels:
        app: pro690-app
    spec:
      containers:
        - image: dnglglmm/pro690-g13-argocd:sha-4d55b0f03427a2e311695b432ed4097f38df568b
          name: pro690-app
          ports:
            - containerPort: 8080
